name: Build
on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore HelpDeskId

    - name: Build
      run: dotnet build HelpDeskId --configuration Release

    - name: Run tests
      run: dotnet test HelpDeskId.Tests --configuration Release --no-build