name: Publish
on:
  push:
    tags:
      - v*
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build NuGet Package
      working-directory: ./HelpDeskId
      run: dotnet pack -p:Version=${GITHUB_REF#refs/tags/v} --configuration Release --output .
    
    - name: Publish NuGet package
      working-directory: ./HelpDeskId
      run: dotnet nuget push HelpDeskId.${GITHUB_REF#refs/tags/v}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json