name: Publish
on:
  push:
    tags:
      - v*
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build NuGet Package
      run: dotnet pack --no-build -Version ${GITHUB_REF#refs/tags/v} --configuration Release --output ${GITHUB_WORKSPACE}/artifacts

    - name: Publish NuGet package
      run: nuget push ${GITHUB_WORKSPACE}/artifacts/HelpDeskId.*.nupkg ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
