name: Publish
on:
  push:
    tags:
      - v*
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build NuGet Package
      run: dotnet pack HelpDeskId/HelpDeskId.csproj -version ${GITHUB_REF#refs/tags/v} --configuration Release --output .
    
    - name: Publish NuGet package
      run: dotnet nuget push HelpDeskId.${GITHUB_REF#refs/tags/v}.nupkg --api-key aaaa --source https://api.nuget.org/v3/index.json