name: Publish
on:
  push:
    tags:
      - v*
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build NuGet Package
      run: dotnet pack --no-build -Version ${GITHUB_REF#refs/tags/v} --configuration Release --output $GITHUB_WORKSPACE/artifacts

    - name: LogLs
      run : ls $GITHUB_WORKSPACE/artifacts

    - name: Publish NuGet package
      run: dotnet nuget push "$GITHUB_WORKSPACE/artifacts/HelpDeskId.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
